kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 28080
    protocol: TCP
  - containerPort: 443
    hostPort: 28443
    protocol: TCP
- role: worker
  labels:
    tier: front
  extraMounts:
  - hostPath: /tmp/worker1
    containerPath: /work
- role: worker
  labels:
    tier: front
  extraMounts:
  - hostPath: /tmp/worker2
    containerPath: /work
- role: worker
  labels:
    tier: back
  extraMounts:
  - hostPath: /tmp/worker3
    containerPath: /work

