apiVersion: v1
kind: Pod
metadata:
  name: inst1-pod
  labels:
    app: inst1app
  namespace: practica2inst1
spec:
  containers:
  - name: web
    # Obliga a descarregar la imatge del repositori
    imagePullPolicy: Always
    image: nginx
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 5
    resources:
      requests:
        memory: "50M"
  - name: cache
    imagePullPolicy: Always
    image: redis
    ports:
    - containerPort: 6379
    resources:
      requests:
        memory: "50M"
  nodeSelector:
    size: Small
