apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: servidor-cache-rs-v3
  namespace: practica2inst3v3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
      appt: cache
  template:
    metadata:
      labels:
        app: webapp
        appt: cache
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: appt
                operator: In
                values:
                - cache
            topologyKey: kubernetes.io/hostname
      containers:
      - name: cache
        image: redis
        ports:
        - containerPort: 6379
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 5
          periodSeconds: 10
  
