apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: servidor-web-rs3
  namespace: practica2inst3v3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
      appt: web
  template:
    metadata:
      labels:
        app: webapp
        appt: web
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: appt
                operator: In
                values:
                - cache
            topologyKey: kubernetes.io/hostname
      containers:
      - name: web
        image: nginx
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
              path: /
              port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
