apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: servidor-web-cache-rs
  namespace: practica2inst3v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - webapp
            topologyKey: kubernetes.io/hostname
      containers:
      - name: cache
        image: redis
        ports:
        - containerPort: 6379
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 5
          periodSeconds: 10
      - name: web
        image: nginx
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
              path: /
              port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
  
