apiVersion: apps/v1
kind: Deployment
metadata:
  name: sist-web-static
  namespace: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-static
  template:
    metadata:
      labels:
        app: web-static
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - web-static
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: web-static
        image:  jlaredo/formacion-static-server-amd64 
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
              path: /
              port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
              path: /
              port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "64M"
            cpu: 100m   
      nodeSelector:
          tier: front
