apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  namespace: backend
spec:
  selector:
    app: postgresql    # Label selector to target the PostgreSQL pods
  ports:
  - protocol: TCP
    port: 5432        # Port on which the Service will listen
    targetPort: 5432  # Port on which the PostgreSQL pods are listening